### ISSUE TITLE
lua-neturl 编译出错，请帮忙看看什么情况？

### ISSUE THREAD

**Issue by jasoncsee** [kenzok8/small#186]
编译环境Ubuntu 22.04
OP官方包
多次编译失败，请帮忙看看哪里出了问题，谢谢
![vmware_uEDBgu6I0G](https://github.com/user-attachments/assets/96a89377-50c3-4192-87d5-d8d609d978b1)

**Comment by GreatMichaelLee** [comment]
这是因为openwrt从2024年11月开始将包管理器从opkg切换到了apk,apk执行更为严格的PKG_VERSION检查，本仓库有好多个包的Makefile里的版本是不符合规范的，两种方法，第一，要么你自己手工改掉Makefile里的版本（规范自己查，比如最好是x.x.x),第二，在make menuconfig->Global Build setting->Use APK instead of OPKG to build distribution, 把这个选项勾去掉，切回opkg管理。

另外希望大佬清理一下仓库里这些包的Makefile版本命令规范。APK包管理器是openwrt的分支主流了。

**Comment by jasoncsee** [comment]
> 这是因为openwrt从2024年11月开始将包管理器从opkg切换到了apk,apk执行更为严格的PKG_VERSION检查，本仓库有好多个包的Makefile里的版本是不符合规范的，两种方法，第一，要么你自己手工改掉Makefile里的版本（规范自己查，比如最好是x.x.x),第二，在make menuconfig->Global Build setting->Use APK instead of OPKG to build distribution, 把这个选项勾去掉，切回opkg管理。
> 
> 另外希望大佬清理一下仓库里这些包的Makefile版本命令规范。APK包管理器是openwrt的分支主流了。

解决了，终于成功编译，非常感谢
